[".local/share/zinit/zinit.git"]
    type = "git-repo"
    url = "https://github.com/zdharma-continuum/zinit.git"
    refreshPeriod = "168h"

[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
    refreshPeriod = "168h"

[".pyenv"]
    type = "git-repo"
    url = "https://github.com/pyenv/pyenv.git"
    refreshPeriod = "168h"

[".pyenv/plugins/pyenv-virtualenv"]
  type = "git-repo"
  url = "https://github.com/pyenv/pyenv-virtualenv.git"
  refreshPeriod = "168h"

[".pyenv/plugins/pyenv-virtualenvwrapper"]
  type = "git-repo"
  url = "https://github.com/pyenv/pyenv-virtualenvwrapper.git"
  refreshPeriod = "168h"

[".jenv"]
    type = "git-repo"
    url = "https://github.com/jenv/jenv.git"
    refreshPeriod = "168h"

[".local/share/nvim/site/pack/packer/start/packer.nvim"]
  type = "git-repo"
  url = "https://github.com/wbthomason/packer.nvim"
  refreshPeriod = "168h"
  [".local/share/nvim/site/pack/packer/start/packer.nvim" .clone]
    args = ["--depth 1"]
