[".local/share/zinit/zinit.git"]
    type = "git-repo"
    url = "https://github.com/zdharma-continuum/zinit.git"
    refreshPeriod = "168h"

[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
    refreshPeriod = "168h"

[".local/share/nvim/site/pack/packer/start/packer.nvim"]
  type = "git-repo"
  url = "https://github.com/wbthomason/packer.nvim"
  refreshPeriod = "168h"

[".asdf"]
  type = "git-repo"
  url = "https://github.com/asdf-vm/asdf.git"
  refreshPeriod = "168h"
  branch = "v0.11.1"

[".emacs.d"]
  type = "git-repo"
  url = "https://github.com/doomemacs/doomemacs"
  refreshPeriod = "168h"

["{{ .fontDir }}/ttf/MesloLGS_NF_Bold_Italic.ttf"]
  type = "file"
  url = "https://github.com/joshholl/dotfiles-old/raw/master/resources/MesloLGS%20NF%20Bold%20Italic.ttf"
  refreshPeriod = "168h"

["{{ .fontDir }}/ttf/MesloLGS_NF_Bold.ttf"]
  type = "file"
  url = "https://github.com/joshholl/dotfiles-old/raw/master/resources/MesloLGS%20NF%20Bold.ttf"
  refreshPeriod = "168h"

["{{ .fontDir }}/ttf/MesloLGS_NF_Italic.ttf"]
  type = "file"
  url = "https://github.com/joshholl/dotfiles-old/raw/master/resources/MesloLGS%20NF%20Italic.ttf"
  refreshPeriod = "168h"

["{{ .fontDir }}/ttf/MesloLGS_NF_Regular.ttf"]
  type = "file"
  url = "https://github.com/joshholl/dotfiles-old/raw/master/resources/MesloLGS%20NF%20Regular.ttf"
  refreshPeriod = "168h"

["{{ .fontDir }}/VictorMono"]
  type = "archive"
  url = "https://rubjo.github.io/victor-mono/VictorMonoAll.zip"
  refreshPeriod = "168h"

["{{ .fontDir }}/ttf/all-the-icons.ttf"]
  type = "file"
  url = "https://github.com/domtronn/all-the-icons.el/raw/master/fonts/all-the-icons.ttf"
  refreshPeriod = "168h"

["{{ .fontDir }}/ttf/file-icons.ttf"]
  type = "file"
  url = "https://github.com/domtronn/all-the-icons.el/raw/master/fonts/file-icons.ttf"
  refreshPeriod = "168h"

["{{ .fontDir }}/ttf/fontawesome.ttf"]
  type = "file"
  url = "https://github.com/domtronn/all-the-icons.el/raw/master/fonts/fontawesome.ttf"
  refreshPeriod = "168h"

["{{ .fontDir }}/ttf/material-design-icons.ttf"]
  type = "file"
  url = "https://github.com/domtronn/all-the-icons.el/raw/master/fonts/material-design-icons.ttf"
  refreshPeriod = "168h"

["{{ .fontDir }}/ttf/octicons.ttf"]
  type = "file"
  url = "https://github.com/domtronn/all-the-icons.el/raw/master/fonts/octicons.ttf"
  refreshPeriod = "168h"

["{{ .fontDir }}/ttf/weathericons.ttf"]
  type = "file"
  url = "https://github.com/domtronn/all-the-icons.el/raw/master/fonts/weathericons.ttf"
  refreshPeriod = "168h"

